language: node_js
node_js:
  - "node"
install:
  - yarn add expo
before_script:
  - cd front-end
script:
  - npm install
  - npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
